services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: datamind-backend
    env_file:
      - ./backend/.env
    ports:
      - "5002:5001"
    depends_on:
      - postgres
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 5001
      FLASK_DEBUG: "true"
      FLASK_ENV: development
      CORS_ORIGIN: http://localhost:5173
      WHISPER_MODEL: base
      UPLOAD_DIR: uploads
      MAX_CONTENT_LENGTH_MB: 100
      DATABASE_URL: postgresql://datamind:datamind@postgres:5432/datamind
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
      - whisper-cache:/root/.cache/whisper
    restart: unless-stopped

  frontend:
    image: node:22-alpine
    container_name: datamind-frontend
    working_dir: /app
    # --legacy-peer-deps: Tiptap v3 sub-packages pin exact @tiptap/core peer versions
    command: sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5001
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: datamind-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=https://ideally-strewn-papyrus.ngrok-free.dev
    volumes:
      - n8n_data:/home/node/.n8n

  postgres:
    image: pgvector/pgvector:pg16
    container_name: datamind-postgres
    environment:
      POSTGRES_USER: datamind
      POSTGRES_PASSWORD: datamind
      POSTGRES_DB: datamind
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: datamind-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  whisper-cache:
  n8n_data:
  frontend_node_modules:
  backend_venv:
  postgres_data:
  pgadmin_data:
